language: go
sudo: false


os: linux
dist: focal
go: 1.14.x

arch:
  - amd64
  - arm64
  
services:
  - docker
#matrix:
  #include:
  #- os: osx
  #  go: 1.14.x  
  #- os: linux
  #  dist: focal
  #  go: 1.14.x
      
notifications:
  email: false

script:
  - docker login -u bhumikapaharia10 -p Root123!@#
  - curl -sL https://taskfile.dev/install.sh | sh
  - travis_wait 40 ./bin/task docker 2> /dev/null
  - ./bin/task ci
