language: go
sudo: false
services:
  - docker
matrix:
  include:
  - os: osx
    go: 1.14.x
  - os: linux
    go: 1.14.x
notifications:
  email: false

script:
  - docker login -u bhumikapaharia10 -p Root123!@#
  - travis_wait 40 make VERSION=1.6.1 build 2> /dev/null
  - curl -sL https://taskfile.dev/install.sh | sh
  - ./bin/task ci
