version: '2'

vars:
  BUILD_DIR: build
  DOCKER_REPO: bhumikapaharia10/github-pr-resource

tasks:
  default:
    cmds:
      - task: test

  generate:
    desc: Generate test fakes
    cmds:
    - go generate ./...
    sources:
    - github.go
    - git.go
    generates:
    - fakes/*.go
    method: checksum

  test:
    desc: Run test suite
    deps: [generate]
    cmds:
    - gofmt -s -l -w .
    - go vet -v ./...
    - go test -race -v ./...

  e2e:
    desc: Run E2E test suite
    cmds:
    - task: test
    - go test -race -v ./... -tags=e2e

  docker:
    desc: Build docker image under dev tag.
    cmds:
    - docker build -t {{.DOCKER_REPO}}:dev .
    #- docker buildx build --platform linux/amd64,linux/arm64 -t {{.DOCKER_REPO}}:dev . --push
    #- mkdir -vp ~/.docker/cli-plugins/
    #- curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
    #- chmod a+x ~/.docker/cli-plugins/docker-buildx
    #- docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
    #- docker buildx create --use --name mybuilder

  build:
    desc: Build check/in/out artifacts
    cmds:
    - task: test
    - task: go-build
      vars: {BINARY: check}
    - task: go-build
      vars: {BINARY: in}
    - task: go-build
      vars: {BINARY: out}

  go-build:
    cmds:
    - go build -o {{.BUILD_DIR}}/{{.BINARY}}{{exeExt}} -ldflags="-s -w" -v cmd/{{.BINARY}}/main.go
    env:
      CGO_ENABLED: '0'
      GOOS: '{{OS}}'
      GOARCH: '{{ARCH}}'

  ci:
    desc: CI build and tests
    cmds:
    - task: build
    #- task: docker 
    - if [ -n "$(git status --porcelain)" ];then echo "Diff in generated files and/or formatting" && exit 1; fi
    silent: true
