#!/bin/bash

export DOCKER_CLI_EXPERIMENTAL=enabled

docker manifest create \
  $DOCKER_REPO:latest \
  $DOCKER_REPO:amd64 \
  $DOCKER_REPO:arm64

docker manifest annotate \
  $DOCKER_REPO:latest \
  $DOCKER_REPO:arm64 --os linux --arch arm64

docker manifest annotate \
  $DOCKER_REPO:latest \
  $DOCKER_REPO:amd64 --os linux --arch amd64

docker manifest push --purge $DOCKER_REPO:latest
