#!/bin/bash
apt-get -y update
apt-get -y --only-upgrade install docker-ee
docker info
#docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
docker run \
  --rm \
  --privileged \
  multiarch/qemu-user-static:register --reset
echo "##################  start buildx tasks  ##################"
docker buildx ls
docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
echo "##################  Create new buildx builder  ##################"
docker buildx create --name mybuilder
echo "##################  Use new buildx builder  ##################"
docker buildx use mybuilder
echo "##################  Inspect buildx builder  ##################"
docker buildx inspect --bootstrap
echo "################## done with pre_build  ##################"
